### ISSUE TITLE
End Goal?

### ISSUE THREAD

**Issue by rrogowski** [rrogowski/RogueAdventure#11]
We should start figuring out what the end goal of the game should be. My friend David made a good recommendation to me. Let the game be a multi-floor dungeon consisting of N floors, starting at floor 1. The goal of each floor is to find the Boss Room. A Boss Room might be a subclass of Room, but it doesn't have to be. All that is special about a Boss Room is that it has a BossMonster (a subclass of monster), which drops a DungeonKey (KeyItem) and maybe another Item (UsableItem?). In each BossRoom, there is also an Elevator (what could this be a subclass of? Is it its own class?), which is only accessible with a DungeonKey. OR, maybe you could try to grab the key if the BossMonster is sleeping. Then the BossMonster receives the "take" action and might have a chance to wake up and attack. The BossMonster drops the DungeonKey on death, which may be used on the Elevator to bring the player to the next floor. The DungeonKey is discarded after use. As the player progresses up through the floors, the Monsters/BossMonsters get harder. On the Nth floor, there is a final BossMonster (what would it drop that would make it worth it to have beaten the game?). After killing the final BossMonster, it drops a DungeonKey (as well as anything else), which can be used on the Elevator to finally escape the dungeon. Upon game completion, whether death or beating all the bosses, the player's score is shown and it congratulates the player for playing and beating the game. One last suggestion: maybe you don't have to kill a BossMonster for every floor. Maybe instead you have to solve a Puzzle. Puzzles can also get harder per floor. For example, on Floor 1, it is a single Switch that you have to flip. Upon solving the Puzzle, you might show the player the message "You heard a ding somewhere in the distance." Then, maybe the Puzzle is no longer Interactable (should Interactable be an abstract class?). When the player enters the room with an Elevator: if the Puzzle is solved, they may use the Elevator. Otherwise, the game might tell the player that there is a Puzzle they must solve on this floor first...

**Comment by zhaomark** [comment]
I like these ideas:
The Boss xor Puzzle idea is great, especially for the first level. It gives the game ebb and rise
N might be 3, 5, or 8 levels, depending on how long we want to run the game
