### ISSUE TITLE
Sense Descriptors

### ISSUE THREAD

**Issue by rrogowski** [rrogowski/RogueAdventure#15]
Upon entering a Room, players might smell the air, feel cold, or hear a noise. When a player drinks a Potion (for example), he/she might have the taste of the Potion described to him/her.

**Comment by rrogowski** [comment]
Starting with the Room, it's possible that when each Room is randomly generated, it has a chance to be associated with a certain smell or sound. Maybe this is encoded as a Room's "sensoryDescription" field or something like that. We want it to be created when the room is generated because the room should retain that description once we leave and come back to that room. Or maybe, the sensory description can be created only when we enter a NEW room. That way, we don't have to tell the player every time they enter the spawn room that "The air smells stale here." Basically, we just want to do some testing with this bit.

**Comment by zhaomark** [comment]
Each room has a value 0, 1, or 2 for feel (hot, normal, cold), smell (bad, normal, good), and noise (silent, ambient, loud).
