### ISSUE TITLE
Taking Weapons/Armor

### ISSUE THREAD

**Issue by rrogowski** [rrogowski/RogueAdventure#16]
Weapons/Armor should be able to be picked up, just like any other item. If you pick up a Weapon/Armor with no respective Item currently equipped, it should log something like "This X increases your Y by Z.", where X is Weapon/Armor name, Y is the stat (damage/defense), and Z is the amount. If the player is wearing a respective Item that he/she picks up, it should say something like "You get rid of the X and put on the Y." where X is the old name and Y is the new name. Then, we need to consider increase/decrease. When logging the increase/decrease, Z should be recalculated to the difference defined as (new stat bonus) - (old stat bonus).

**Comment by zhaomark** [comment]
Temp solution: after killing an enemy, the player has a chance of improving their damage or defense by the dungeonLevel
We can implement the original plan if necessary.

**Comment by rrogowski** [comment]
I like it!
