### ISSUE TITLE
Proposed Exp to Stats

### ISSUE THREAD

**Issue by zhaomark** [rrogowski/RogueAdventure#21]
![balance](https://cloud.githubusercontent.com/assets/7322209/6400544/935dc0f6-bdc7-11e4-96c1-1fb0d3a25fce.png)
How do you feel about this stats curve? (the numbers are a bit weird) 
I can send you the excel file, if you want.
On a successful attack: attacked_hp - (attacker_dmg - attacked_def)
On a successful kill: attacker_exp += attacked_exp
The player should really only see one level below, one level equal, and one above. The player starts at level 1. The bat should be level 0.

if lvl is linear,
required exp is exponential,
dmg is exponential-ish
def is cubic
hp is quadratic

**Comment by rrogowski** [comment]
Curve looks great across the board. Only issue is the "On successful attack" formula. If enemy defense is higher than player damage, hit points are added to the attacked creatures health. What about instead the damage is max(attacker_damage - attacked_defense, 0)? That way, damage is always >= 0.
