### ISSUE TITLE
Our First Presentable Prototype

### ISSUE THREAD

**Issue by rrogowski** [rrogowski/RogueAdventure#30]
Here are some ideas for when we know our first prototype is completed:

1. The whole game might contain the following: Shops, a detailed boss battle, descriptions of monsters, sensory descriptions of Rooms or objects (when picked up, when used, etc.).
2. Once we beat the boss and enter the Ladder or Elevator or whatever, we should generate the next floor and place the player inside (this actually might not have to be the case for our first prototype).
3. We have tested many run-throughs together with no errors or funky behavior.

Mark, I would love your feedback to see if you think we should have anything else for our first prototype before we present it to Dr. Bishop!

**Comment by zhaomark** [comment]
'Tis a good roadmap. 2 is easy once we have something that checks if a level is complete.
