### ISSUE TITLE
New map format

### ISSUE THREAD

**Issue by zhaomark** [rrogowski/RogueAdventure#31]
Floats are messy
The current map integer values:
Thousands: difficulty (1: spawn, 2: easy, 3: equal, 4: hard)
Hundreds/Tens/Ones: descriptors (0: negative, 1: neutral, 2: pleasant)

What do you think?

**Comment by rrogowski** [comment]
Yes I like this. Makes comparison a lot more stable since we can directly compare integers instead of floats.
