### ISSUE TITLE
Combat

### ISSUE THREAD

**Issue by rrogowski** [rrogowski/RogueAdventure#45]
Combat may be too hard. Potions may help with this, but it seems like killing the boss would be really hard at this stage. The highest the boss has damaged me was for 14 hitpoints over the course of the whole battle. We only have 5 hitpoints when we start, so maybe the boss needs to be toned down? Play around with some values and once we have potions implemented (hopefully soon) we can fix this issue.

**Comment by zhaomark** [comment]
Refactored the enemy stats system to generate based on player's stats and ring number.
Might implement a touch of randomness in the future.
