### ISSUE TITLE
Game Too Easy Now?

### ISSUE THREAD

**Issue by rrogowski** [rrogowski/RogueAdventure#49]
With relative ease, I am able to kill the boss on the fourth floor without taking any damage. Maybe the bosses should be amped up a little bit?

**Comment by rrogowski** [comment]
UPDATE: changing the line "player.damage += player.dungeonLevel + 1;" to "player.damage = player.dungeonLevel + 1;" made the levels significantly more challenging, but still doable if one faces enough monsters before the bosses.

**Comment by zhaomark** [comment]
Changed above to player.damage++ and player.defense++.
Changed Boss HP as well: instead of abs, using max(1, dmg - def)
